APP_PORT=3001

SWAGGER_PATH=docs

JWT_SECRET=very-secure-secret-token
JWT_EXPIRES_IN=30d

MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USER=root
MYSQL_PASSWORD=root
MYSQL_DB_NAME=leadgen
MYSQL_TEST_DB_NAME=test

DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME}"
DATABASE_TEST_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_TEST_DB_NAME}"